"""
Regression tests against the original NumPy implementation (commit 9ecc0ec).

Golden values were generated by running the pre-PyTorch NumPy code on
fixed-seed datasets (numpy.random.default_rng, seeds 42 and 7).

Two kinds of assertions:

1.  Numeric goldens for the Xuan & Murphy likelihoods, whose math is
    unchanged. The old driver had an off-by-one: it passed ``s + 1`` to a
    ``pdf`` that itself incremented ``s``, so old ``P[t, s]`` covered
    ``data[t:s+2]``. The current driver's ``P[t, s]`` covers ``data[t:s+1]``,
    hence old ``P[t, s]`` is compared with new ``P[t, s+1]``. (The old last
    column is skipped entirely: its formula used a segment length one larger
    than the actual segment.)

2.  Behavioral goldens: detected changepoint locations must match the known
    true segment boundaries. StudentT log-likelihood *values* are not
    compared: the old implementation approximated the marginal likelihood by
    evaluating all points under the final posterior predictive, while the
    current implementation computes the exact closed form (see
    test_studentt_exactness.py).
"""

import pytest
import torch

np = pytest.importorskip("numpy")

from functools import partial

from bayesian_changepoint_detection import offline_likelihoods
from bayesian_changepoint_detection.bayesian_models import (
    offline_changepoint_detection,
)
from bayesian_changepoint_detection.priors import const_prior

# --- fixed-seed datasets (identical to the golden-generation script) --------


def univariate_dataset():
    rng = np.random.default_rng(42)
    return np.concatenate(
        [
            rng.normal(0.0, 1.0, 50),
            rng.normal(5.0, 0.5, 50),
            rng.normal(-2.0, 2.0, 50),
        ]
    )


def multivariate_dataset():
    rng = np.random.default_rng(7)
    return np.concatenate(
        [
            rng.multivariate_normal([0, 0], np.eye(2), 40),
            rng.multivariate_normal([3, -3], [[1.0, 0.6], [0.6, 1.0]], 40),
            rng.multivariate_normal([0, 2], [[0.5, 0.0], [0.0, 2.0]], 40),
        ]
    )


# --- golden P values from the NumPy implementation (interior entries only) --

NUMPY_P_GOLDENS = {
    "independent_features": {
        (0, 10): -33.49239382238292,
        (40, 79): -214.21910997812358,
        (80, 110): -107.73580418256245,
        (25, 60): -176.1089697866527,
        (100, 117): -67.82178069150712,
        (5, 5): -4.004141725841441,
        (39, 41): -21.27808871160984,
        (60, 90): -159.41826675853315,
        (110, 118): -35.48324176286132,
    },
    "full_covariance": {
        (0, 10): -33.49561642361253,
        (0, 60): -237.80880271583015,
        (40, 79): -187.15544674846052,
        (80, 110): -109.68843967101708,
        (25, 60): -151.08321081465863,
        (100, 117): -69.4966926989705,
        (5, 5): -4.681159231594379,
        (39, 41): -19.58813555422497,
        (60, 90): -147.25077785867256,
        (110, 118): -35.32907449405947,
    },
}

LIKELIHOOD_CLASSES = {
    "independent_features": offline_likelihoods.IndependentFeaturesLikelihood,
    "full_covariance": offline_likelihoods.FullCovarianceLikelihood,
}


def top_peaks(Pcp, k=2, min_distance=5):
    """Indices of the k largest well-separated changepoint probabilities."""
    probs = torch.exp(Pcp).sum(0)
    order = torch.argsort(probs, descending=True)
    peaks = []
    for idx in order.tolist():
        if all(abs(idx - p) >= min_distance for p in peaks):
            peaks.append(idx)
        if len(peaks) == k:
            break
    return sorted(peaks)


@pytest.mark.parametrize("name", ["independent_features", "full_covariance"])
def test_xuan_likelihood_values_match_numpy(name):
    data = torch.tensor(multivariate_dataset())
    likelihood = LIKELIHOOD_CLASSES[name](device="cpu")
    for (t, s_old), expected in NUMPY_P_GOLDENS[name].items():
        # old P[t, s] covered data[t:s+2]  ->  new pdf(data, t, s+2)
        value = likelihood.pdf(data, t, s_old + 2)
        assert value == pytest.approx(expected, abs=1e-6), (
            f"{name}: segment [{t}, {s_old + 2}) diverged from NumPy golden"
        )


@pytest.mark.parametrize("name", ["independent_features", "full_covariance"])
def test_xuan_detection_locations(name):
    data = torch.tensor(multivariate_dataset())
    prior = partial(const_prior, p=1.0 / (len(data) + 1))
    _, _, Pcp = offline_changepoint_detection(
        data,
        prior,
        LIKELIHOOD_CLASSES[name](device="cpu"),
        truncate=-40,
        device="cpu",
    )
    peaks = top_peaks(Pcp)
    # true boundaries at 40 and 80; allow the +-2 jitter the NumPy version
    # also showed (it detected 37/38 and 79/81)
    assert len(peaks) == 2
    assert abs(peaks[0] - 40) <= 3
    assert abs(peaks[1] - 80) <= 3


def test_studentt_detection_locations():
    data = torch.tensor(univariate_dataset())
    prior = partial(const_prior, p=1.0 / (len(data) + 1))
    _, _, Pcp = offline_changepoint_detection(
        data,
        prior,
        offline_likelihoods.StudentT(device="cpu"),
        truncate=-40,
        device="cpu",
    )
    peaks = top_peaks(Pcp)
    # true boundaries at 50 and 100; the NumPy version peaked at 49 and 98
    assert len(peaks) == 2
    assert abs(peaks[0] - 50) <= 3
    assert abs(peaks[1] - 100) <= 3

    # the two peaks must carry substantial probability mass
    probs = torch.exp(Pcp).sum(0)
    assert probs[peaks[0]] > 0.3
    assert probs[peaks[1]] > 0.3


def test_offline_multivariate_t_detection_locations():
    # No NumPy-era counterpart exists for the offline MultivariateT model;
    # assert the behavioral contract only.
    data = torch.tensor(multivariate_dataset())
    prior = partial(const_prior, p=1.0 / (len(data) + 1))
    _, _, Pcp = offline_changepoint_detection(
        data,
        prior,
        offline_likelihoods.MultivariateT(device="cpu"),
        truncate=-40,
        device="cpu",
    )
    peaks = top_peaks(Pcp)
    assert len(peaks) == 2
    assert abs(peaks[0] - 40) <= 3
    assert abs(peaks[1] - 80) <= 3
